@host = http://localhost

GET {{host}}/orders
Host: order.localhost

###

GET {{host}}/orders/5f798a4fb2b1652689f8588d
Host: order.localhost

###

POST {{host}}/orders
Host: order.localhost
Content-Type: application/json

{
  "products": [
    {
      "product": "5f799da9cb1e271ee9b2ab00",
      "quantity": 10
    }
  ],
  "shippingName": "neversitup",
  "shippingAddress": "silom"
}

###

PUT {{host}}/orders/5f798a4fb2b1652689f8588d
Host: order.localhost
Content-Type: application/json

{
  "cancel": true
}